spring:
    freemarker:
        allow-request-override: false # HttpServletRequest中的属性是否可以覆盖controller中的model的同名项目
        allow-session-override: false # HttpSession的属性是否可以覆盖controller中model的同名项
        cache: false # 是否开启缓存
        charset: UTF-8 # 模板文件编码
        check-template-location: true # 是否检查模板文件位置
        content-type: text/html
        expose-request-attributes: false #是否将HttpServletRequest中的属性添加到model
        expose-session-attributes: false # 是否将HttpSession中的属性添加到model中
        expose-spring-macro-helpers: false
        suffix: .ftl
        template-loader-path: classpath:/templates/